# Generated by Django 5.0.3 on 2024-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_ticket_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.AddField(
            model_name='engineer',
            name='image_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
