# Generated by Django 5.0.3 on 2024-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('helpdesk', '0003_alter_ticket_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='statuses',
            field=models.ManyToManyField(blank=True, to='helpdesk.status'),
        ),
    ]
